"""Modular detection and temporal-linking primitives for AceTree."""

from .api import (
    TRACKING_API_MAJOR,
    TRACKING_API_VERSION,
    Calibration,
    ComponentSpec,
    Detection,
    TrackEdge,
    TrackerGraphResult,
    TrackingOutcome,
    TrackingRequest,
    TrackingResult,
    TrackingScope,
    WholeMoviePreflightContext,
)
from .detectors import DoGDetector, DogDetector, LoGDetector, LogDetector
from .lap import LAPTracker, SimpleLAPTracker
from .starrynite import (
    StarryNiteDetector,
    StarryNiteDivisionTracker,
    StarryNiteLegacyExactTracker,
    StarryNiteTracker,
    StarryNiteTuningProfile,
    load_tuning_profile,
)
from .integration import ApplyTrackingProposal, TrackingProposalConflict
from .persistence import (
    TrackingProposalFormatError,
    read_tracking_proposal,
    tracking_sidecar_path,
    write_tracking_proposal,
)
from .pipeline import TrackingCancelled, TrackingPipeline
from .proposals import trim_selected_forward_result
from .registry import (
    ComponentDescriptor,
    PluginContribution,
    TrackingRegistry,
    build_default_registry,
    get_default_registry,
)
from .workflows import (
    CUSTOM_COMPONENTS,
    DOG_LAP,
    FORWARD_TRACKING_WORKFLOWS,
    GLOBAL_TRACKING_WORKFLOWS,
    INITIAL_TRACKING_WORKFLOWS,
    LEGACY_STARRYNITE_EXACT,
    LOG_LAP,
    MODERN_STARRYNITE,
    TrackingWorkflow,
    tracking_workflow,
    workflow_for_components,
)

__all__ = [
    "TRACKING_API_MAJOR",
    "TRACKING_API_VERSION",
    "Calibration",
    "CUSTOM_COMPONENTS",
    "ApplyTrackingProposal",
    "ComponentDescriptor",
    "ComponentSpec",
    "Detection",
    "DOG_LAP",
    "DoGDetector",
    "DogDetector",
    "LAPTracker",
    "LEGACY_STARRYNITE_EXACT",
    "LOG_LAP",
    "LoGDetector",
    "LogDetector",
    "PluginContribution",
    "FORWARD_TRACKING_WORKFLOWS",
    "GLOBAL_TRACKING_WORKFLOWS",
    "INITIAL_TRACKING_WORKFLOWS",
    "MODERN_STARRYNITE",
    "SimpleLAPTracker",
    "StarryNiteDetector",
    "StarryNiteDivisionTracker",
    "StarryNiteLegacyExactTracker",
    "StarryNiteTracker",
    "StarryNiteTuningProfile",
    "TrackEdge",
    "TrackerGraphResult",
    "TrackingOutcome",
    "TrackingRegistry",
    "TrackingCancelled",
    "TrackingPipeline",
    "TrackingProposalConflict",
    "TrackingProposalFormatError",
    "TrackingRequest",
    "TrackingResult",
    "TrackingScope",
    "TrackingWorkflow",
    "WholeMoviePreflightContext",
    "build_default_registry",
    "get_default_registry",
    "load_tuning_profile",
    "read_tracking_proposal",
    "tracking_sidecar_path",
    "trim_selected_forward_result",
    "tracking_workflow",
    "workflow_for_components",
    "write_tracking_proposal",
]
